set_property SRC_FILE_INFO {cfile:{D:/Licenta/Licenta/PROIECT LICENTA  FINAL/project_1/project_1.srcs/constrs_1/new/AES_CONSTR.xdc} rfile:../../../project_1.srcs/constrs_1/new/AES_CONSTR.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports clk]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports rx]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U11 [get_ports tx]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports rst]
